# Generated by Django 3.2.20 on 2023-07-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
